// Font families — the single source of truth for every typeface in the app.
//
// ⚠️ REWRITTEN for the shelf redesign (docs/SHELF_REDESIGN.md, decisions D1 + D3).
// Inter is out; the design's stacks are in. Every KEY is unchanged, so call sites
// keep compiling — only the stacks moved.
//
// ⚠️ Webfonts must be loaded in index.html for these to render as intended:
//   - "Instrument Sans"  → primary Latin UI font (Google Fonts)
//   - "Instrument Serif" → Latin display / hero text
//   - "JetBrains Mono"   → labels, metadata, numerics — a LOAD-BEARING role in this
//                          design, not just code. Mono uppercase is how every overline,
//                          count and timestamp is set (`.lab`, `.k`, `.meta`).
//   - "Noto Sans SC"     → Simplified-Chinese glyphs
//   - "Noto Serif SC"    → CJK fallback under `serif`, for the hero character
//   - "Material Symbols Rounded" → the icon face (D3); see `.ms` in src/index.css and
//                          the <Icon> wrapper in src/components/Icon.tsx
// If a face is missing the browser silently falls back down the stack.
export const FONTS = {
    // Primary UI font for all Latin text (labels, body, headings, buttons).
    sans: '"Instrument Sans", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',

    // CJK text — characters, foreign words, mixed-script blocks. Unchanged by the
    // redesign: the design's --cjk is this same stack.
    cjk: '"Noto Sans SC", "Noto Sans JP", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',

    // Sub-character component glyphs (word search No Pinyin hint row). "HanziComponents"
    // is a self-hosted subset of Noto Sans SC covering the component glyphs Google's
    // frequency-subset webfont omits (⺮ ⺼ 㐬 …); it is listed FIRST so those glyphs
    // resolve locally, and the browser falls back per glyph to the same face for
    // everything else — so the seam is invisible. Declared in src/index.css; the file is
    // generated by server/scripts/backfill/chinese/generate-component-font.js.
    //
    // ⚠️ DELIBERATELY UNTOUCHED by the redesign. This is a self-hosted subset keyed to
    // Noto Sans SC's metrics; swapping either face here breaks the seamless fallback.
    hanziComponents:
        '"HanziComponents", "Noto Sans SC", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',

    // Serif — Latin display text, and the giant headword character on the card-detail
    // page. TWO faces on purpose: Instrument Serif has NO CJK coverage, so a Chinese
    // headword falls through per glyph to Noto Serif SC and still renders as a serif
    // rather than dropping to the OS sans. Same per-glyph fallback trick as
    // `hanziComponents` above. Removing "Noto Serif SC" here silently un-serifs every
    // CJK hero character.
    serif: '"Instrument Serif", "Noto Serif SC", Georgia, serif',

    // Numeric / code / numbered-tone pinyin — and, in this design, every mono overline,
    // count, badge and timestamp. Carries far more of the UI than the name suggests.
    mono: '"JetBrains Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace',

    // The icon face (D3). Not used directly in `sx` — go through <Icon name="..." />,
    // which owns the ligature settings that make `nights_stay` render as a glyph
    // instead of as the literal word.
    icons: '"Material Symbols Rounded"',
} as const;
