-- Migration 124: document the per-(sense, POS) shape of dictionaryentries_zh."longDefinition"
--
-- COMMENT-ONLY. No data or type change: the column is already `jsonb` (migration 70),
-- and both the old and new shapes live in it side by side during the rollout.
--
-- Migration 70 converted `longDefinition` from TEXT to a JSONB OBJECT keyed by part of
-- speech ({"noun": "...", "verb": "..."}) and its COMMENT still says so. As of
-- backfill-long-definitions.js v15 the zh shape is a JSONB ARRAY with one element per
-- (SENSE, PART OF SPEECH) pair:
--
--   [{"sense": "<definitionClusters label>", "pos": "<one POS>", "definition": "..."}, ...]
--
-- The sense is a `definitionClusters` cluster (migration 90) and `sense` is the join key
-- to it and to the learner's per-card `vocabentries.selectedSense` (migration 99). SEVERAL
-- ELEMENTS MAY SHARE A `sense` — a cluster whose `pos` lists more than one role gets one
-- definition per role, because the roles mean different things (坏 adjective = the state
-- "it is broken", verb = the event "it breaks down").
--
-- DELIBERATELY NOT DONE HERE: old per-POS objects are NOT nulled out (unlike migration 70,
-- which discarded the pre-jsonb text). The read boundary still renders them, so rows keep
-- working until `backfill-long-definitions.js --stale` regenerates them, and rows whose
-- `definitions` field a validator has reviewed keep their approved object indefinitely.
-- See docs/LONGDEF_PER_SENSE_MIGRATION.md.
--
-- Spanish is unchanged: `dictionaryentries_es` has no sense clusters, so
-- spanish/backfill-long-definitions.js still writes the per-POS object.
--
-- Idempotent: COMMENT ON is a full replace, so re-running is a no-op.

COMMENT ON COLUMN dictionaryentries_zh."longDefinition" IS
  'AI-generated definition elaboration as a JSONB ARRAY, one element per (sense, part-of-speech) pair: [{"sense": "<definitionClusters label>", "pos": "<one POS>", "definition": "<nuance>"}]. Several elements may share a sense (one per POS it takes). Ordered default-sense-first, then the cluster''s own pos order; 25-200 chars per definition. Generated by server/scripts/backfill/chinese/backfill-long-definitions.js (v15+). Learner surfaces are served ONE sense at a time (server/utils/definitions.ts resolveLongDefinition); the validator review document is served every pair (longDefToDisplayString). Rows not yet regenerated still hold the legacy per-POS object {"<pos>": "<nuance>"} and are read through the same helpers.';

COMMENT ON COLUMN dictionaryentries_es."longDefinition" IS
  'AI-generated definition elaboration as a JSONB object keyed by part of speech: {"<pos>": "<nuance>"}. Single-POS = one key. Spanish has no definitionClusters, so it keeps the per-POS shape (the zh table is per (sense, POS) pair as of migration 124). Distinct from `etymology` (Wiktionary etymology text). Written by server/scripts/backfill/spanish/backfill-long-definitions.js.';
