-- Migration 70: Convert `longDefinition` from TEXT to JSONB on both det tables
--
-- `longDefinition` is the AI-generated definition elaboration shown in the eip
-- definition tab. Previously a single labeled TEXT blob ("noun: ... \n\n verb: ...").
-- It now stores a JSONB OBJECT keyed by part of speech, one value per POS:
--
--   { "noun": "<nuance for the noun sense>", "verb": "<nuance for the verb sense>" }
--
-- Single-POS words store a one-key object ({ "noun": "..." }). Each value is an
-- independent definition with its own length budget (25–125 chars per value; see
-- backfill-long-definitions.js maxLenForPos / MAX_LEN_PER_POS).
--
-- Why JSONB: the object form lets the generator agent emit one definition per POS
-- cleanly (instead of a hand-labeled string that downstream code has to re-parse),
-- and budgets each sense independently rather than splitting one shared character
-- pool across all senses.
--
-- Read boundary: the API still serves longDefinition to clients as the old labeled
-- string (the object is joined back into "pos: ... \n\n pos: ..." form when hydrating
-- entities), so longDefinitionParts segmentation and the frontend renderer are
-- unchanged. The JSONB object is an internal storage/enrichment detail.
--
-- Existing values: the old TEXT elaborations are written under the prior budget and
-- labeling scheme, so they are DISCARDED here (set NULL) and regenerated in object
-- form by backfill-long-definitions.js (which selects rows WHERE longDefinition IS NULL).
-- For es the column was already NULL everywhere (etymology lives in `etymology`).
--
-- Idempotent: guarded by a data_type check so a re-run is a no-op once converted.

DO $$
BEGIN
  IF (SELECT data_type FROM information_schema.columns
      WHERE table_name = 'dictionaryentries_zh' AND column_name = 'longDefinition') = 'text' THEN
    -- Discard old text elaborations; they are re-backfilled in object form.
    UPDATE dictionaryentries_zh SET "longDefinition" = NULL WHERE "longDefinition" IS NOT NULL;
    ALTER TABLE dictionaryentries_zh
      ALTER COLUMN "longDefinition" TYPE jsonb USING NULL::jsonb;
  END IF;

  IF (SELECT data_type FROM information_schema.columns
      WHERE table_name = 'dictionaryentries_es' AND column_name = 'longDefinition') = 'text' THEN
    UPDATE dictionaryentries_es SET "longDefinition" = NULL WHERE "longDefinition" IS NOT NULL;
    ALTER TABLE dictionaryentries_es
      ALTER COLUMN "longDefinition" TYPE jsonb USING NULL::jsonb;
  END IF;
END$$;

COMMENT ON COLUMN dictionaryentries_zh."longDefinition" IS
  'AI-generated definition elaboration as a JSONB object keyed by part of speech: {"<pos>": "<nuance>"}. Single-POS = one key. Each value is 25-125 chars. Generated by server/scripts/backfill/chinese/backfill-long-definitions.js. Served to clients as a labeled "pos: ... \n\n pos: ..." string (see longDefObjectToDisplayString).';

COMMENT ON COLUMN dictionaryentries_es."longDefinition" IS
  'AI-generated definition elaboration as a JSONB object keyed by part of speech: {"<pos>": "<nuance>"}. Single-POS = one key. Distinct from `etymology` (Wiktionary etymology text). Currently NULL pending the Spanish object-form long-definitions backfill.';
