import { useEffect, useMemo, useState } from 'react';
import { CanvasSource, Texture, TilingSprite } from 'pixi.js';
import { extend } from '@pixi/react';
import { isoToScreen, TILE_WIDTH, TILE_HEIGHT } from '../../engine/market/isometric';
import { freeFarmTileset, FARM_TILE_PX } from '../../engine/market/freeFarmTileset';
import nmpPerf from './nmpPerf';

extend({ TilingSprite });

/**
 * GroundBackdropLayer — the infinite default ground behind the market: one repeating
 * tallDirt + lightGrass motif that fills the whole viewport at any pan/zoom
 * (docs/NIGHT_MARKET_FEATURE.md § "Default ground apron").
 *
 * LAYER: view. Draws ONE `TilingSprite`, so its cost is independent of zoom.
 *
 * WHY IT EXISTS. The first cut of the apron padded the real tile field out to the camera's entire
 * zoomed-out reach — ~200×200 cells, 40k+ sprites, rebuilt through React on every frame. This layer
 * replaces the bulk of that with a single quad: {@link ./TemplateTerrainLayer} now draws only the
 * market plus a thin `APRON_RING_CELLS` ring of real autotiled tiles, and everything past the ring
 * is this backdrop.
 *
 * WHY IT IS SEAMLESS. Every interior ground cell resolves to the same two sprites — the `center`
 * tallDirt slab under the `center` lightGrass cap — so the rendered ground is exactly periodic. The
 * iso screen lattice is generated by (W/2, −H/2) and (−W/2, −H/2), so it contains (W, 0) (cell
 * +1col −1row) and (0, H) (cell +1col +1row): ANY `TILE_WIDTH × TILE_HEIGHT` window of the infinite
 * uniform ground is therefore a correct repeating unit. We take that window at a known cell corner
 * so `tilePosition` can re-phase it against cell (0,0), which lines the backdrop's diamonds up
 * cell-for-cell with the real tiles. The ring exists so the market's edge tiles autotile against
 * in-field neighbours (see `boundless` in {@link ../../engine/market/farmTerrain padTerrainField})
 * and never draw a plateau cliff.
 *
 * WHY CANVAS2D AND NOT `renderer.generateTexture`. The bake used to go through the Pixi renderer,
 * which made a purely-static piece of art depend on WebGL state, `Application` init ordering, the
 * renderer's own `resolution` (2 on HiDPI resamples pixel art), and `Matrix.shared`. Every one of
 * those failure modes produces a *blank* texture, and a blank backdrop is pixel-identical to a
 * missing one — the bug is invisible. Compositing on a 2D canvas instead is synchronous, resolution-
 * exact, independent of the renderer's lifecycle, and — crucially — lets us read the result back
 * with `getImageData` and FAIL LOUDLY if it is not fully opaque (see `assertOpaque`).
 *
 * ⚠️ The sprite stack here MUST match {@link ./EditorTerrainLayer}'s (slab at `y + TILE_HEIGHT`,
 * cap at `y`, both bottom-centre anchored). That layer is the source of truth; if its anchors or
 * z-slots change, the generated motif drifts out of alignment with the real tiles and a visible
 * seam appears at the ring boundary.
 */

/**
 * Drawn BELOW every ground tile. Ground z is `-(col + row) + slot`, which is unbounded below as the
 * continent grows, so this is a deliberately absurd constant rather than a near miss.
 */
const BACKDROP_Z = -1e12;

/**
 * Cells of uniform ground composited before cropping the motif. The crop is taken at the centre
 * cell, and its window is covered by that cell's diamond plus its four cardinal neighbours' — so
 * ≥2 cells of margin on every side is what guarantees the window is fully painted.
 */
const MOTIF_PATCH_CELLS = 9;

/** Positive modulo — JS `%` keeps the sign of the dividend, which would mis-phase the tiling. */
const mod = (n: number, m: number) => ((n % m) + m) % m;

/** Decode one tileset PNG into something `drawImage` accepts, independent of Pixi's asset cache. */
async function loadImage(url: string): Promise<HTMLImageElement> {
  const img = new Image();
  img.src = url;
  // `decode()` rejects on a broken URL, which surfaces as the caller's console.error.
  await img.decode();
  return img;
}

/**
 * Verify the baked motif is 100% opaque. A hole here is not cosmetic: the backdrop is the bottom of
 * the scene, so any transparent pixel becomes a repeating grid of see-through dots across the whole
 * viewport. Returns the number of non-opaque pixels (0 = good).
 */
function countTransparent(pixels: Uint8ClampedArray): number {
  let n = 0;
  for (let i = 3; i < pixels.length; i += 4) if (pixels[i] < 255) n += 1;
  return n;
}

/**
 * Build the tileable ground motif: composite a uniform patch of interior ground tiles onto a 2D
 * canvas, cropping to one lattice period as we draw (the canvas IS the crop — the patch is drawn
 * translated so the wanted window sits at the canvas origin).
 */
async function generateMotif(): Promise<Texture | null> {
  // The exact pair an interior cell resolves to: both in their `center` autotile variant.
  const slabUrl = freeFarmTileset.getTallDirt('center');
  const capUrl = freeFarmTileset.getGrassBase('light', 'center');
  if (!slabUrl || !capUrl) {
    // Loud on purpose: a missing stem means no backdrop at all, and a silent null here is
    // indistinguishable from a working transparent backdrop.
    console.error('[nmp] ground backdrop: tileset is missing tallDirt_center / lightGrass_center', { slabUrl, capUrl });
    return null;
  }

  const [slabImg, capImg] = await Promise.all([loadImage(slabUrl), loadImage(capUrl)]);

  const canvas = document.createElement('canvas');
  canvas.width = TILE_WIDTH;
  canvas.height = TILE_HEIGHT;
  const ctx = canvas.getContext('2d', { willReadFrequently: true });
  if (!ctx) {
    console.error('[nmp] ground backdrop: could not get a 2d context for the motif canvas');
    return null;
  }
  ctx.imageSmoothingEnabled = false; // pixel art: never resample

  // The window we keep, in patch-local screen px: the centre cell's diamond band. The grass cap is
  // 32×32 art whose diamond occupies its BOTTOM TILE_HEIGHT rows, and the cap is drawn with its
  // bottom edge on `screenY` — so the diamond band is [screenY − TILE_HEIGHT, screenY].
  const centre = Math.floor(MOTIF_PATCH_CELLS / 2);
  const { screenX: cropCx, screenY: cropCy } = isoToScreen(centre, centre);
  const cropX = cropCx - TILE_WIDTH / 2;
  const cropY = cropCy - TILE_HEIGHT;

  // Painter's order: FAR cells first so near ones overdraw them, matching the scene's
  // `z = -(col + row)` sort. Iterating col/row naively would paint far over near and let a slab's
  // cliff band cover the cap in front of it.
  const cells: Array<{ col: number; row: number }> = [];
  for (let col = 0; col < MOTIF_PATCH_CELLS; col++) {
    for (let row = 0; row < MOTIF_PATCH_CELLS; row++) cells.push({ col, row });
  }
  cells.sort((a, b) => (b.col + b.row) - (a.col + a.row));

  for (const { col, row } of cells) {
    const { screenX, screenY } = isoToScreen(col, row);
    // Mirrors EditorTerrainLayer: slab a tile-height lower, cap on top, both bottom-centred —
    // i.e. top-left of a bottom-centre-anchored FARM_TILE_PX sprite is (x − W/2, y − FARM_TILE_PX).
    const left = screenX - TILE_WIDTH / 2 - cropX;
    ctx.drawImage(slabImg, left, screenY + TILE_HEIGHT - FARM_TILE_PX - cropY);
    ctx.drawImage(capImg, left, screenY - FARM_TILE_PX - cropY);
  }

  const holes = countTransparent(ctx.getImageData(0, 0, TILE_WIDTH, TILE_HEIGHT).data);
  if (holes === TILE_WIDTH * TILE_HEIGHT) {
    console.error('[nmp] ground backdrop: baked motif is fully transparent — nothing will render', { slabUrl, capUrl });
    return null;
  }
  if (holes > 0) {
    console.error(`[nmp] ground backdrop: baked motif has ${holes} non-opaque px — expect a see-through dot grid`);
  }

  // Built explicitly rather than via `Texture.from` so the source type is unambiguous — `from`
  // routes through autodetect + the global asset cache, neither of which we want for a one-off bake.
  const texture = new Texture({
    source: new CanvasSource({ resource: canvas, scaleMode: 'nearest', antialias: false }),
  });
  nmpPerf.note('backdrop', `motif ${texture.width}×${texture.height}, holes ${holes}`);
  return texture;
}

export default function GroundBackdropLayer({
  pan,
  zoom,
  viewportW,
  viewportH,
}: {
  pan: { x: number; y: number };
  zoom: number;
  viewportW: number;
  viewportH: number;
}) {
  const [motif, setMotif] = useState<Texture | null>(null);

  // The motif is pure art — no world, camera or renderer input — so it is baked ONCE on mount.
  useEffect(() => {
    let cancelled = false;
    generateMotif()
      .then((tex) => { if (!cancelled) setMotif(tex); })
      // Never swallow: without the backdrop the market sits on bare background, and the failure is
      // otherwise invisible (a transparent quad looks exactly like a missing one).
      .catch((err) => { console.error('[nmp] ground backdrop: motif generation failed', err); });
    return () => { cancelled = true; };
  }, []);

  // The viewport expressed in camera-LOCAL px (the space this layer's parent container lives in):
  // the inverse of `container.x = viewportW/2 + pan.x, scale = zoom`. A one-tile bleed keeps the
  // edges covered against rounding.
  const rect = useMemo(() => {
    const bleed = TILE_WIDTH;
    const left = (-viewportW / 2 - pan.x) / zoom - bleed;
    const top = (-viewportH / 2 - pan.y) / zoom - bleed;
    return {
      x: left,
      y: top,
      width: viewportW / zoom + bleed * 2,
      height: viewportH / zoom + bleed * 2,
    };
  }, [pan, zoom, viewportW, viewportH]);

  if (!motif || viewportW <= 0 || viewportH <= 0) return null;

  // Re-phase the pattern so texture pixel (0,0) lands on a lattice point. The crop was taken at
  // camera-local (−W/2, −H) + k·(W, 0) + m·(0, H), so that is the congruence `tilePosition` must
  // restore relative to the quad's own origin.
  const tilePosition = {
    x: mod(-TILE_WIDTH / 2 - rect.x, TILE_WIDTH),
    y: mod(-TILE_HEIGHT - rect.y, TILE_HEIGHT),
  };

  return (
    <pixiTilingSprite
      texture={motif}
      x={rect.x}
      y={rect.y}
      width={rect.width}
      height={rect.height}
      tilePosition={tilePosition}
      zIndex={BACKDROP_Z}
      eventMode="none"
    />
  );
}
