/**
 * Word Search — fixed 7×6 placement templates (fallback path).
 *
 * See docs/WORD_SEARCH_TEMPLATES.md for the full design. Used by
 * `generateWordSearchGrid` (wordSearchGrid.ts) once random snaking placement
 * has failed `RANDOM_GRID_ATTEMPTS` whole-grid regenerations in a row.
 *
 * Sized for TOTAL_WORDS = 9 (12 → 9 on 2026-08-28, when the board shrank from
 * 9×6 to 7×6): each template tiles the same fixed 6-hole 7×6 pattern (the four
 * board corners + the two cells at the grid's center — the cells NOT covered by
 * any slot below) into 9 disjoint "slots," each an ordered path of exactly 4
 * orthogonally-adjacent cells. A word of length 4 fills a whole slot; a shorter
 * word takes a random contiguous run within its slot (see wordSearchGrid.ts),
 * leaving the rest of that slot as ordinary filler. 36 of the 42 cells are slot
 * cells (86% full) — essentially the same density the 12-word 9×6 board had
 * (48 of 54, 89%), so random placement is still expected to fall back to
 * template mode often; template mode guarantees a fit by construction regardless.
 *
 * Generated by a one-off backtracking tiling script (not at runtime) and
 * verified for: exactly 9 pieces of exactly 4 cells, every consecutive pair
 * within a piece orthogonally adjacent, no piece cell adjacent to more than 2
 * same-piece cells (rules out T/plus-shaped pieces, which can't be walked as
 * a single path), no piece closing into a 2×2 loop (a cycle would read as a
 * word in several directions), no overlaps, and full coverage of the 36
 * non-hole cells.
 */

export interface WordSearchTemplate {
  /** 9 slots, each an ordered path of exactly 4 [row, col] cells. */
  slots: [number, number][][];
}

export const WORD_SEARCH_TEMPLATE_ROWS = 7;
export const WORD_SEARCH_TEMPLATE_COLS = 6;

export const WORD_SEARCH_TEMPLATE_HOLES: [number, number][] = [
  [0, 0], [0, 5], [3, 2], [3, 3], [6, 0], [6, 5],
];

export const WORD_SEARCH_TEMPLATES: WordSearchTemplate[] = [
  {
    slots: [
      [[0, 1], [0, 2], [1, 2], [2, 2]],
      [[0, 3], [1, 3], [2, 3], [2, 4]],
      [[0, 4], [1, 4], [1, 5], [2, 5]],
      [[1, 0], [1, 1], [2, 1], [3, 1]],
      [[2, 0], [3, 0], [4, 0], [5, 0]],
      [[3, 4], [3, 5], [4, 5], [5, 5]],
      [[4, 1], [5, 1], [6, 1], [6, 2]],
      [[4, 2], [5, 2], [5, 3], [6, 3]],
      [[4, 3], [4, 4], [5, 4], [6, 4]],
    ],
  },
  {
    slots: [
      [[0, 1], [0, 2], [0, 3], [1, 3]],
      [[0, 4], [1, 4], [1, 5], [2, 5]],
      [[1, 0], [1, 1], [1, 2], [2, 2]],
      [[2, 0], [2, 1], [3, 1], [4, 1]],
      [[2, 3], [2, 4], [3, 4], [3, 5]],
      [[3, 0], [4, 0], [5, 0], [5, 1]],
      [[4, 4], [4, 3], [4, 2], [5, 2]],
      [[4, 5], [5, 5], [5, 4], [5, 3]],
      [[6, 1], [6, 2], [6, 3], [6, 4]],
    ],
  },
  {
    slots: [
      [[0, 1], [1, 1], [2, 1], [3, 1]],
      [[0, 3], [0, 2], [1, 2], [2, 2]],
      [[0, 4], [1, 4], [1, 3], [2, 3]],
      [[1, 0], [2, 0], [3, 0], [4, 0]],
      [[1, 5], [2, 5], [2, 4], [3, 4]],
      [[3, 5], [4, 5], [4, 4], [4, 3]],
      [[4, 2], [4, 1], [5, 1], [5, 0]],
      [[5, 2], [5, 3], [5, 4], [5, 5]],
      [[6, 1], [6, 2], [6, 3], [6, 4]],
    ],
  },
  {
    slots: [
      [[0, 1], [0, 2], [0, 3], [0, 4]],
      [[1, 0], [2, 0], [3, 0], [3, 1]],
      [[1, 1], [2, 1], [2, 2], [2, 3]],
      [[1, 2], [1, 3], [1, 4], [2, 4]],
      [[1, 5], [2, 5], [3, 5], [3, 4]],
      [[4, 0], [5, 0], [5, 1], [6, 1]],
      [[4, 1], [4, 2], [5, 2], [6, 2]],
      [[4, 5], [4, 4], [4, 3], [5, 3]],
      [[5, 5], [5, 4], [6, 4], [6, 3]],
    ],
  },
  {
    slots: [
      [[0, 1], [0, 2], [1, 2], [2, 2]],
      [[0, 3], [1, 3], [2, 3], [2, 4]],
      [[0, 4], [1, 4], [1, 5], [2, 5]],
      [[1, 0], [1, 1], [2, 1], [3, 1]],
      [[2, 0], [3, 0], [4, 0], [5, 0]],
      [[3, 4], [3, 5], [4, 5], [5, 5]],
      [[4, 1], [4, 2], [5, 2], [5, 3]],
      [[4, 3], [4, 4], [5, 4], [6, 4]],
      [[5, 1], [6, 1], [6, 2], [6, 3]],
    ],
  },
  {
    slots: [
      [[0, 1], [0, 2], [1, 2], [1, 3]],
      [[0, 3], [0, 4], [1, 4], [1, 5]],
      [[1, 0], [1, 1], [2, 1], [3, 1]],
      [[2, 0], [3, 0], [4, 0], [5, 0]],
      [[2, 2], [2, 3], [2, 4], [3, 4]],
      [[2, 5], [3, 5], [4, 5], [4, 4]],
      [[4, 3], [4, 2], [4, 1], [5, 1]],
      [[5, 3], [5, 2], [6, 2], [6, 1]],
      [[5, 5], [5, 4], [6, 4], [6, 3]],
    ],
  },
  {
    slots: [
      [[0, 1], [0, 2], [1, 2], [1, 3]],
      [[0, 3], [0, 4], [1, 4], [2, 4]],
      [[1, 1], [1, 0], [2, 0], [3, 0]],
      [[1, 5], [2, 5], [3, 5], [4, 5]],
      [[2, 3], [2, 2], [2, 1], [3, 1]],
      [[3, 4], [4, 4], [4, 3], [5, 3]],
      [[4, 0], [4, 1], [4, 2], [5, 2]],
      [[5, 0], [5, 1], [6, 1], [6, 2]],
      [[5, 5], [5, 4], [6, 4], [6, 3]],
    ],
  },
  {
    slots: [
      [[0, 1], [1, 1], [1, 0], [2, 0]],
      [[0, 2], [1, 2], [1, 3], [2, 3]],
      [[0, 3], [0, 4], [1, 4], [2, 4]],
      [[1, 5], [2, 5], [3, 5], [4, 5]],
      [[2, 2], [2, 1], [3, 1], [4, 1]],
      [[3, 0], [4, 0], [5, 0], [5, 1]],
      [[3, 4], [4, 4], [4, 3], [4, 2]],
      [[5, 2], [5, 3], [5, 4], [5, 5]],
      [[6, 1], [6, 2], [6, 3], [6, 4]],
    ],
  },
  {
    slots: [
      [[0, 1], [1, 1], [1, 2], [1, 3]],
      [[0, 2], [0, 3], [0, 4], [1, 4]],
      [[1, 0], [2, 0], [3, 0], [4, 0]],
      [[1, 5], [2, 5], [3, 5], [4, 5]],
      [[2, 1], [2, 2], [2, 3], [2, 4]],
      [[3, 1], [4, 1], [5, 1], [5, 0]],
      [[3, 4], [4, 4], [4, 3], [5, 3]],
      [[4, 2], [5, 2], [6, 2], [6, 1]],
      [[5, 5], [5, 4], [6, 4], [6, 3]],
    ],
  },
  {
    slots: [
      [[0, 1], [1, 1], [2, 1], [2, 2]],
      [[0, 2], [1, 2], [1, 3], [2, 3]],
      [[0, 3], [0, 4], [1, 4], [1, 5]],
      [[1, 0], [2, 0], [3, 0], [3, 1]],
      [[2, 4], [3, 4], [4, 4], [4, 3]],
      [[2, 5], [3, 5], [4, 5], [5, 5]],
      [[4, 0], [5, 0], [5, 1], [6, 1]],
      [[4, 1], [4, 2], [5, 2], [5, 3]],
      [[5, 4], [6, 4], [6, 3], [6, 2]],
    ],
  },
  {
    slots: [
      [[0, 1], [1, 1], [2, 1], [2, 2]],
      [[0, 2], [1, 2], [1, 3], [2, 3]],
      [[0, 3], [0, 4], [1, 4], [1, 5]],
      [[1, 0], [2, 0], [3, 0], [3, 1]],
      [[2, 4], [2, 5], [3, 5], [4, 5]],
      [[3, 4], [4, 4], [4, 3], [5, 3]],
      [[4, 0], [4, 1], [4, 2], [5, 2]],
      [[5, 0], [5, 1], [6, 1], [6, 2]],
      [[5, 5], [5, 4], [6, 4], [6, 3]],
    ],
  },
];
