import { numberedToTonedPinyin, readingSyllableCount } from './pinyinTones.js';

/**
 * Pure utility for computing short definitions from a definitions array.
 * Deterministic — no AI, no DB, no external dependencies.
 *
 * Algorithm:
 * 1. Filter out definitions that are grammatical notes (starting with '(' or 'CL:')
 * 2. Split remaining definitions by '; ' to get individual senses
 * 3. Strip trailing parenthetical content (e.g. "(informal, ...)")
 * 4. Return the shortest surviving token
 * 5. If all definitions were filtered out, fall back to unfiltered tokens
 */
export function generateShortDefinition(definitions: string[]): string | null {
  if (!definitions || definitions.length === 0) {
    return null;
  }

  const candidates: string[] = [];

  for (const def of definitions) {
    // Skip definitions that are purely grammatical notes
    const trimmed = def.trim();
    if (trimmed.startsWith('(') || trimmed.startsWith('CL:')) {
      continue;
    }

    // Split by '; ' to get individual senses
    const senses = trimmed.split('; ');

    for (const sense of senses) {
      // Strip trailing parenthetical content
      const stripped = sense.replace(/ \([^)]+\)$/, '').trim();
      if (stripped.length > 0) {
        candidates.push(stripped);
      }
    }
  }

  // Fall back to unfiltered tokens if all definitions were filtered out
  if (candidates.length === 0) {
    for (const def of definitions) {
      const senses = def.trim().split('; ');
      for (const sense of senses) {
        const stripped = sense.replace(/ \([^)]+\)$/, '').trim();
        if (stripped.length > 0) {
          candidates.push(stripped);
        }
      }
    }
  }

  if (candidates.length === 0) {
    return null;
  }

  // Return the token with the fewest characters
  return candidates.reduce((shortest, current) =>
    current.length < shortest.length ? current : shortest
  );
}

/**
 * LEGACY stored shape of `longDefinition`: a JSONB object keyed by part of speech
 * ({ "noun": "...", "verb": "..." }). Still the CURRENT shape for Spanish
 * (`dictionaryentries_es`, spanish/backfill-long-definitions.js) and for any zh row
 * not yet regenerated by the sense-aware backfill.
 */
export type LongDefinitionObject = Record<string, string>;

/**
 * CURRENT stored shape for Chinese: one entry per (SENSE, PART OF SPEECH) PAIR — the sense
 * being a `definitionClusters` cluster (docs/DEFINITION_CLUSTERS.md). A cluster whose `pos`
 * lists several roles contributes SEVERAL entries sharing one `sense`, because the roles
 * carry different meanings (坏 adjective = the state "it is broken", verb = the event "it
 * breaks down"). Written by chinese/backfill-long-definitions.js in default-sense-first
 * order (the same highest-frequency-first order the flp sense-picker uses) and, within a
 * sense, in the cluster's own `pos` order — so element 0 is the fallback when a caller has
 * no clusters to resolve against.
 */
export interface LongDefinitionSense {
  sense: string;            // cluster `sense` LABEL — the join key to definitionClusters/selectedSense
  pos?: string | null;      // ONE of the parts of speech this sense takes
  definition: string;       // what the word means in THIS sense AND this grammatical role
}

/** Any shape the `longDefinition` column can hold at read time. */
export type LongDefinitionValue = LongDefinitionSense[] | LongDefinitionObject | string;

/** True for the per-sense array shape (zh); false for the legacy per-POS object. */
function isSenseArray(value: unknown): value is LongDefinitionSense[] {
  return Array.isArray(value);
}

/** Normalized, non-empty sense entries of an array-shaped value. */
function senseEntries(value: LongDefinitionSense[]): LongDefinitionSense[] {
  return value.filter(
    (s): s is LongDefinitionSense =>
      !!s && typeof s === 'object' && typeof s.definition === 'string' && s.definition.trim().length > 0
  );
}

/**
 * Read boundary for `longDefinition` when EVERY sense/POS must be shown — the validator
 * review document (validationBodyFormat) and its approval-freshness twin. Joins the
 * stored value into one labeled string:
 *
 * - per-sense array (zh) → `"<sense> (<pos>): ...\n\n<sense> (<pos>): ..."`; a lone
 *   sense renders bare (no label), matching the single-POS behavior below.
 * - per-POS object (es/legacy) → `"pos: ...\n\npos: ..."`, single-POS renders bare.
 * - string → passthrough (already-hydrated callers).
 *
 * Empty values are dropped; an empty/absent value yields null.
 *
 * NOTE: this is NOT what the learner sees on the eip/cdp — that surface shows only the
 * sense they picked (see `resolveLongDefinition`).
 */
export function longDefToDisplayString(
  value: LongDefinitionValue | null | undefined
): string | null {
  if (value == null) return null;
  if (typeof value === 'string') return value || null;

  if (isSenseArray(value)) {
    const entries = senseEntries(value);
    if (entries.length === 0) return null;
    if (entries.length === 1) return entries[0].definition.trim();
    return entries
      .map((s) => {
        const label = s.pos ? `${s.sense} (${s.pos})` : s.sense;
        return `${label}: ${s.definition.trim()}`;
      })
      .join('\n\n');
  }

  const segments = Object.entries(value)
    .filter(([, def]) => typeof def === 'string' && def.trim().length > 0)
    .map(([pos, def]) => ({ pos, def: def.trim() }));

  if (segments.length === 0) return null;
  if (segments.length === 1) return segments[0].def;
  return segments.map(({ pos, def }) => `${pos}: ${def}`).join('\n\n');
}

/**
 * Unwrap INLINE MORPHEMES before the aside scanner runs.
 *
 * A parenthetical GLUED to a word (no space on at least one side) whose content is a
 * short run of lowercase letters is part of the word, not an aside about it:
 *   "personal(ly)" · "child(ren)" · "circle(s)" · "remain(s)" · "(hand)bag"
 * Deleting it turns an adverb into an adjective — 手's cluster gloss "personal(ly)"
 * used to reach the flashcard as the bare adjective "personal", which is how 下手's
 * breakdown came to read that way.
 *
 * The `^[a-z]{1,4}$` content test is what separates these from a real aside that
 * merely lost its space — "skimming(of milk)", "prescription(same as 丹方)",
 * "(idiom)fig." — which are shaped IDENTICALLY at the parenthesis and must still be
 * stripped. Adjacency alone cannot tell the two apart; only the content can.
 * Measured against the whole det corpus (2026-08-28): fires on 50 of the 118 glued
 * strings, declines all 12 missing-space asides and all 35 chemical/math formulas
 * ("Ca(OH)2", "(CH2O)6" — uppercase or digit-bearing content).
 *
 * Two accepted errors at that threshold, both on non-discoverable rows:
 *   • misses the longer optional prefixes — "(house)wife", "(roller)blading",
 *     "(tender)loin" render as "wife" / "blading" / "loin";
 *   • fires wrongly on "manganese(iv) oxide" → "manganeseiv oxide".
 * Widening the cap past 4 starts eating "(idiom)", so 4 is the balance point.
 */
const INLINE_MORPHEME = /(?<=[A-Za-z0-9])\(([a-z]{1,4})\)|\(([a-z]{1,4})\)(?=[A-Za-z0-9])/g;

function unwrapInlineMorphemes(text: string): string {
  return text.replace(INLINE_MORPHEME, (_match, glued, prefix) => glued ?? prefix);
}

/**
 * Strip all parenthetical substrings from a definition string for display.
 * Does not mutate the underlying database value.
 * e.g. "to go (informal); to leave (a place)" → "to go; to leave"
 * Nesting-aware: "a waiter (literally, one who runs (fast))" → "a waiter".
 * EXCEPTION — a short lowercase parenthetical glued to a word is an inline morpheme,
 * not an aside, and is rejoined rather than dropped: "personal(ly)" → "personally",
 * "(hand)bag" → "handbag". See unwrapInlineMorphemes for the exact rule.
 *
 * Server twin of `stripParentheses` in `src/utils/definitionUtils.ts` — kept in
 * sync manually (separate client/server builds).
 */
export function stripParentheses(text: string): string {
  // Inline morphemes are rejoined FIRST; everything the scanner then sees is a
  // genuine aside. See unwrapInlineMorphemes above for why the split is by content.
  text = unwrapInlineMorphemes(text);
  let out = '';
  let depth = 0;
  for (const ch of text) {
    // A '(' at any depth opens/deepens an aside; a ')' closes one. Tracking depth
    // (rather than the old /\s*\([^)]*\)/g) is what makes NESTED asides work: the
    // regex stopped at the FIRST ')', so 的's gloss — which nests a parenthetical
    // inside a quoted example — leaked its tail onto the flashcard.
    // Eat any whitespace already emitted before the aside, reproducing the old
    // regex's leading `\s*` — without this, "to go (informal); to leave" would
    // render "to go ; to leave" and "[+de (particle)]" would render "[+de ]".
    if (ch === '(') { if (depth === 0) out = out.replace(/\s+$/, ''); depth++; continue; }
    // An unmatched ')' (depth already 0) is dropped rather than kept: a lone close
    // paren is never displayable text, and it is exactly what 加 used to render.
    if (ch === ')') { if (depth > 0) depth--; continue; }
    if (depth === 0) out += ch;
  }
  return out.trim();
}

/**
 * Display Definition Transformation (ddt) — the per-cluster analog of dd
 * (`definitions[0]` stripped of parentheticals). A cluster's `glosses` are already
 * ordered prototypical→vernacular within the sense (backfill Stage B), so the lead
 * gloss is the cluster's own "definitions[0]". Used server-side by the example-
 * sentence segment enrichment to render a segment's tagged sense as its dd.
 * Server twin of `ddt` in `src/utils/definitionUtils.ts`. See docs/DEFINITION_CLUSTERS.md.
 */
export function ddt(cluster: { glosses: string[] }): string {
  return stripParentheses(cluster.glosses[0] ?? '');
}

/**
 * Resolve a component character's context-correct display gloss: find the
 * character's `definitionClusters` entry whose `sense` label equals `senseLabel`
 * and return its `ddt`. This is the single "gloss array from the char's det entry
 * keyed on the sense string, then ddt" operation — the same mapping the
 * breakdown-sense backfill materializes into `breakdown[char].definition`, exposed
 * for read-time callers (word-search grid build). Returns null when there are no
 * clusters, no sense label, or no cluster matches that label — the caller decides
 * the fallback (e.g. the stored breakdown definition). See docs/DEFINITION_CLUSTERS.md.
 */
export function resolveSenseGloss(
  clusters: Array<{ sense?: string | null; glosses?: string[] | null }> | null | undefined,
  senseLabel: string | null | undefined
): string | null {
  if (!Array.isArray(clusters) || !senseLabel) return null;
  const match = clusters.find((c) => c && c.sense === senseLabel && Array.isArray(c.glosses));
  if (!match) return null;
  const gloss = ddt({ glosses: match.glosses as string[] });
  return gloss || null;
}

// Inline cluster shape (avoids a circular dependency with server/types/index.ts).
type SenseCluster = {
  sense?: string | null;
  glosses?: string[] | null;
  frequencyScore?: number | null;
  // Numbered pinyin for THIS sense (zh only; null for es). See resolveDisplayPronunciation.
  reading?: string | null;
};

/**
 * The ONE sense-pick rule, shared by every server-side "which sense is this card on?"
 * read (`resolveDisplayDefinition` for dd, `resolveLongDefinition` for the extended
 * definition). Mirrors the client's `sortedSenseClusters` + `resolveSelectedSenseIndex`
 * exactly: clusters sorted highest-vernacular-first (nulls last) so index 0 is the
 * default/starred sense, and `selectedSense` matched by LABEL (stable across
 * re-clustering — an unmatched label falls back to the default).
 *
 * Returns null when there is no real choice to make (unclustered, or a single cluster) —
 * the same `< 2` gate the client applies — so callers use their flat fallback.
 *
 * The sort is STABLE and the comparator ties on equal scores, so two equally-common senses
 * are separated by the stored array order — which the backfill authors deliberately (zh
 * Stage C.5 / es CLUSTER_RULES rule 7, docs/DEFINITION_CLUSTERS.md § Ties). Preserve that
 * order on any path that reshapes `definitionClusters`.
 *
 * Clusters with no displayable English (a lead gloss that is entirely parenthetical, e.g.
 * 上来 "(verb complement indicating success)") are dropped before that gate, mirroring the
 * client's `sortedSenseClusters` — they are not offered in the picker, so the server must
 * not resolve a card onto one either. Label-addressed reads (`resolveSenseGloss`) are
 * unaffected and still see every cluster.
 * See docs/DEFINITION_CLUSTERS.md.
 */
export function resolveSelectedCluster(entry: {
  definitionClusters?: SenseCluster[] | null;
  selectedSense?: string | null;
}): SenseCluster | null {
  const clusters = entry.definitionClusters;
  if (!Array.isArray(clusters)) return null;
  const displayable = clusters.filter(
    (c) => c && Array.isArray(c.glosses) && ddt({ glosses: c.glosses as string[] }) !== ''
  );
  if (displayable.length < 2) return null;
  const sorted = displayable.sort((a, b) => (b?.frequencyScore ?? -1) - (a?.frequencyScore ?? -1));
  const idx = entry.selectedSense ? sorted.findIndex((c) => c && c.sense === entry.selectedSense) : -1;
  return sorted[idx >= 0 ? idx : 0] ?? null;
}

/**
 * Read boundary for `longDefinition` on LEARNER surfaces (eip Definition tab, cdp) —
 * the extended definition for the ONE sense the card is currently on, never the whole
 * set. The per-sense array (zh) is addressed by the same sense pick that drives dd, so
 * the long definition and the gloss above it always describe the same sense.
 *
 * Resolution order for the array shape:
 *   1. the entry whose `sense` label equals the resolved cluster's label (the learner's
 *      `selectedSense`, else the default/starred sense) — ALL of its entries, since a sense
 *      used in more than one grammatical role stores one definition per role,
 *   2. the entries sharing element 0's sense — the backfill writes default-sense-first, so
 *      that is the right answer whenever the payload carries no clusters or the labels have
 *      drifted apart (re-clustered since the last longDefinition run).
 *
 * A sense with several POS renders as labeled blocks (`"adjective: …\n\nverb: …"`), the same
 * shape the per-POS object has always produced — so the renderer's `pre-line` handling is
 * unchanged. A single-POS sense renders bare.
 *
 * The legacy per-POS object (Spanish, and zh rows not yet regenerated) has no sense
 * dimension, so it falls through to the all-senses join — behavior there is unchanged.
 */
export function resolveLongDefinition(
  value: LongDefinitionValue | null | undefined,
  entry: { definitionClusters?: SenseCluster[] | null; selectedSense?: string | null } = {}
): string | null {
  const entries = longDefEntriesForSense(value, entry);
  if (entries === null) {
    // Not the per-sense array shape — string passthrough / legacy object join.
    if (value == null) return null;
    if (typeof value === 'string') return value || null;
    return longDefToDisplayString(value);
  }
  return joinSenseEntries(entries);
}

/**
 * The entries of a per-sense `longDefinition` that belong to the card's CURRENT sense (one
 * per part of speech that sense takes), in stored order. Returns `null` when `value` isn't
 * the per-sense array shape, so callers can fall back; `[]` when it is but nothing matches.
 *
 * Shared by `resolveLongDefinition` (which joins them into the display string) and the DAL's
 * per-sense payload build, so "which entries is this card on?" is decided in exactly one place.
 */
export function longDefEntriesForSense(
  value: LongDefinitionValue | null | undefined,
  entry: { definitionClusters?: SenseCluster[] | null; selectedSense?: string | null } = {}
): LongDefinitionSense[] | null {
  if (value == null || typeof value === 'string' || !isSenseArray(value)) return null;

  const entries = senseEntries(value);
  if (entries.length === 0) return [];

  const label = resolveSelectedCluster(entry)?.sense;
  const matched = label ? entries.filter((s) => s.sense === label) : [];
  // No pick (or a drifted label) ⇒ the default sense, i.e. everything sharing element 0's label.
  return matched.length > 0 ? matched : entries.filter((s) => s.sense === entries[0].sense);
}

/**
 * Join one sense's entries into the displayed string: bare for a single part of speech,
 * `"<pos>: …"` blocks separated by a blank line when the sense takes several.
 */
export function joinSenseEntries(entries: LongDefinitionSense[]): string | null {
  if (entries.length === 0) return null;
  if (entries.length === 1) return entries[0].definition.trim() || null;
  return entries
    .map((s) => (s.pos ? `${s.pos}: ${s.definition.trim()}` : s.definition.trim()))
    .join('\n\n');
}

/**
 * Server twin of `resolveDisplayDefinition` in `src/utils/definitionUtils.ts` — the dd
 * for a vet-backed entry, honoring the learner's per-card sense pick.
 *
 * Used where the SERVER, not the client, materializes a card's English text into a
 * payload that no longer carries the clusters (the Word Search word list). Client-side
 * surfaces must use the client twin instead of re-implementing this.
 *
 * Mirrors the client ordering exactly: clusters sorted highest-vernacular-first (nulls
 * last) so index 0 is the default/starred sense, `selectedSense` matched by LABEL (stable
 * across re-clustering), and a fallback to `stripParentheses(definitions[0])` whenever the
 * entry is unclustered, has a single cluster, or the chosen cluster has no usable gloss.
 * See docs/DEFINITION_CLUSTERS.md.
 */
export function resolveDisplayDefinition(entry: {
  definition?: string | null;
  definitionClusters?: SenseCluster[] | null;
  selectedSense?: string | null;
}): string {
  const legacyDd = stripParentheses(entry.definition ?? '');
  const chosen = resolveSelectedCluster(entry);
  if (!chosen || !Array.isArray(chosen.glosses)) return legacyDd;
  return ddt({ glosses: chosen.glosses as string[] }) || legacyDd;
}

/**
 * Server twin of `readingCluster` in `src/utils/definitionUtils.ts` — the cluster whose
 * `reading` supplies an entry's DISPLAY pinyin. Split out of `resolveDisplayPronunciation`
 * because pinyin and dd resolve through DIFFERENT gates; see the asymmetry note there.
 *
 * Two paths, in order:
 *   1. **A real sense choice exists** (`resolveSelectedCluster`, ≥2 displayable clusters) —
 *      use that pick, so the reading belongs to the same sense whose English the payload
 *      carries. Honors the learner's `selectedSense` label exactly as dd does.
 *   2. **No choice to make** (unclustered, or fewer than two displayable clusters). The dd
 *      side is showing the flat `definitions[0]`, so there is no chosen sense to agree with;
 *      return the entry's PRIMARY reading — the highest-frequency cluster, preferring one
 *      that carries displayable English so a gloss-less grammatical-particle cluster cannot
 *      donate its reading to a real gloss's card.
 *
 * The client twin takes a `senseIndexOverride` for a pick made in-session; the server only
 * ever sees the persisted `selectedSense`, so there is no override parameter here.
 */
function readingCluster(entry: {
  definitionClusters?: SenseCluster[] | null;
  selectedSense?: string | null;
}): SenseCluster | null {
  const clusters = entry.definitionClusters;
  if (!Array.isArray(clusters) || clusters.length === 0) return null;

  const chosen = resolveSelectedCluster(entry);
  if (chosen) return chosen;

  const displayable = clusters.filter(
    (c) => c && Array.isArray(c.glosses) && ddt({ glosses: c.glosses as string[] }) !== ''
  );
  const pool = displayable.length > 0 ? displayable : clusters.filter(Boolean);
  return [...pool].sort((a, b) => (b?.frequencyScore ?? -1) - (a?.frequencyScore ?? -1))[0] ?? null;
}

/**
 * Server twin of `resolveDisplayPronunciation` in `src/utils/definitionUtils.ts` — the
 * DISPLAY pinyin for a vet-backed entry, honoring the learner's per-card sense pick.
 *
 * A heteronym's reading belongs to its sense, not to the word (过去 = `guò qù` "the past"
 * vs `guò qu` the directional suffix), so every payload that materializes a sense-resolved
 * definition must materialize the matching reading beside it — otherwise the surface prints
 * one sense's English over another sense's tones. Used wherever the clusters do NOT travel
 * to the client (the sort/discover flow, the Study Challenge word cards, the community feed,
 * the Word Search word list, the related-words / used-in lists); client-side surfaces resolve
 * locally with the client twin.
 *
 * **Why this does NOT share `resolveDisplayDefinition`'s `< 2` displayable-cluster gate.**
 * The two fields have different fallbacks. dd falls back to `definitions[0]`, a CURATED
 * artifact — a hand-ordered lead gloss that is often the better string, so bailing to it when
 * there is no sense to choose is a real editorial choice. Pinyin has no second artifact:
 * `pronunciation`/`numberedPinyin` is the same fact stored twice, and the column is the
 * UNREVIEWED copy. backfill-cluster-definitions.js seeds the model with the column as
 * "primary reading", instructs it to override for genuine heteronyms, and writes back ONLY
 * `definitionClusters` — so the column is upstream-of-review by construction and drifts in
 * one direction forever (重点 kept `chong2 dian3` in the column long after its clusters were
 * corrected to `zhong4 dian3`). Gating pinyin on `< 2` would pin the ~74% of discoverable
 * entries that are single-cluster to that unreviewed copy.
 *
 * Returns the entry-level `pronunciation` column whenever there is no cluster reading to use
 * — unclustered (the ~110k non-discoverable det rows), Spanish (whose clusters carry no
 * reading), or a reading whose syllable count disagrees with the column (cpcd zips syllables
 * to characters positionally, so a mis-shaped reading would shift every character's pinyin
 * one column). See docs/DEFINITION_CLUSTERS.md.
 */
export function resolveDisplayPronunciation(entry: {
  pronunciation?: string | null;
  definitionClusters?: SenseCluster[] | null;
  selectedSense?: string | null;
}): string | null {
  const columnPinyin = entry.pronunciation ?? null;
  const reading = readingCluster(entry)?.reading;
  if (!reading) return columnPinyin;
  const toned = numberedToTonedPinyin(reading);
  if (!toned) return columnPinyin;
  if (columnPinyin && readingSyllableCount(toned) !== readingSyllableCount(columnPinyin)) {
    return columnPinyin;
  }
  return toned;
}

// Inline type to avoid a circular dependency with server/types/index.ts
type ShortDefinitionPronunciationOverride = { definition?: string | null; pronunciation?: string | null };

/**
 * Resolve the short definition for a dictionary entry.
 * Returns the manual override if one is set; otherwise falls back to generateShortDefinition().
 */
export function resolveShortDefinition(definitions: string[], override?: ShortDefinitionPronunciationOverride | null): string | null {
  if (override?.definition != null) return override.definition;
  return generateShortDefinition(definitions);
}

/**
 * The COLLISION KEY for an entry's dd — what "these two cards read the same" means.
 *
 * Two different vet entries can resolve to the identical display definition (个 and
 * 位 both dd as "measure word"; 高兴 and 开心 both as "happy"). On a flashcard that is
 * harmless — the learner sees one card at a time — but inside a GAME every surface is
 * simultaneous: two bubbles, two Match Speed rows, two grid words, two map labels all
 * showing "happy", with only one of them counting as the right answer for a given
 * prompt. That is not a hard puzzle, it is an unanswerable one, so no game may ever
 * show two entries with the same key at the same time.
 *
 * Normalization is deliberately loose (case, surrounding/collapsed whitespace, and a
 * trailing period), because the confusion is VISUAL: "Happy" beside "happy" reads as a
 * duplicate to a player even though the strings differ. It is deliberately NOT
 * semantic — "happy" and "glad" are two distinct answers a player can tell apart, and
 * collapsing near-synonyms would thin the candidate pool for no gain.
 *
 * Returns '' for an entry with no usable dd. An EMPTY KEY NEVER COLLIDES: callers must
 * skip it rather than treat every gloss-less card as a duplicate of every other one.
 *
 * No client twin today: every game's round is assembled SERVER-side (the game pool,
 * the Word Search grid, the Memory Map spawn), so the guard lives at those three
 * chokepoints alone. A future surface that composes a round on the client — Study
 * Challenge words riding a game's slots, say — needs a matching normalizer in
 * `src/utils/definitionUtils.ts`, and it must normalize IDENTICALLY or the two guards
 * will disagree about what a duplicate is.
 *
 * Referenced by docs/GAMES_FEATURE.md § "No two cards may share a dd in one round".
 */
export function ddCollisionKey(entry: {
  definition?: string | null;
  definitionClusters?: SenseCluster[] | null;
  selectedSense?: string | null;
}): string {
  return resolveDisplayDefinition(entry)
    .trim()
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .replace(/\.$/, '');
}
